name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup config.json
      run: |
        sed -i 's/$MAIL_FROM/${{ secrets.MAIL_FROM }}/' src/config.json
        sed -i 's/$MAIL_TO/${{ secrets.MAIL_TO }}/' src/config.json
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          source: "*"
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          target: ${{ secrets.REMOTE_TARGET }}
